name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/amd64/v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_PAT }}
      - name: Build & Push Backend Docker image
        run: docker buildx build -t ghcr.io/vincentkelleher/verifiable-credential-playground-backend:latest --platform linux/arm64,linux/amd64,linux/amd64/v2 ./backend --push
      - name: Build & Push Frontend Docker image
        run: docker buildx build -t ghcr.io/vincentkelleher/verifiable-credential-playground-frontend:latest --platform linux/arm64,linux/amd64,linux/amd64/v2 ./frontend --push
